mode: "train"
arc_type: sl
out_root: "../result/20181126/sl"

loader:
  data_type: raw
  input_type: tfrecord
  raw_dir_params:
    input_dir: ../data/train_cv/cv_0001

trainer:
  network_params:
    network_type: sl
    classifier_params:
      conv_params:
        layer_type: midi
        n_dim: 64
      feature_type: gap
      mlp_params:
        hidden_layers: []        
  loss_params:     
  update_params:
     opt_type: "adam"
     lrate_params:
       l_rate: 0.001
     
  graph_dir: "graph"
  save_model_path: "models/model"
#  load_model_path: "models/model"
  logger_params:  
    log_dir: "logs"
    metrics: ["acc", "ent", "iou"]
    metric_period: 1

runner:
  epochs: 500
  batch_size: 32
  eval_params:
    eval_dir: "acc"
    n_out: 100

