mode: "eval"
loader:
  data_type: mnist
  raw_dir_params:
    data_dir: ../data/test1
    resize: [190, 140]

trainer:
  train_type: ae
  model_arch:
    arch_type: cnn_ae
    conv_params:
      layer_type: small
      n_dim: 4

    feature_layer: vae
    mlp_params:
      hidden_layers: []
    tconv_params:
      n_up: 2
      i_channel: 16
  loss_params: 0
  opt_params:
     opt_type: "adam"
     l_rate: 0.001
#    decay_type: step
#     decay_epoch: 10
#     decay_factor: 0.5
     decay_type: exp
     decay_rate: 0.075
     
  graph_dir: "./graph"
  logger_params:
    log_dir: logs
    metrics: ["acc"]
    metric_period: 1
#  save_model_path: "models/model"
  load_model_path: "models/model"
runner:
  epochs: 20
  batch_size: 32
  eval_params:
    eval_dir: "eval2"
    n_out: 100

